spring.application.name=SGDisposals
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=5

server.address=0.0.0.0
server.port=8080
