spring.application.name=SGDisposals
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=5

server.address=0.0.0.0
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subashsg7777@gmail.com
spring.mail.password=fklc acvz buzb tupj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.url = rediss://default:AYtXAAIncDE1YTE4ZjJkYTc3MmI0N2IzOTI3NDQ0Y2UxOWU2ZTMzMHAxMzU2NzE@simple-koi-35671.upstash.io:6379

rate-limit.login.limit = 5
rate-limit.login.window-seconds=30

rate-limit.search.limit=20
rate-limit.search.window-seconds=30

# Aliases for RateLimitType keys used in code
rate-limit.high.limit=5
rate-limit.high.window-seconds=30

rate-limit.medium.limit=20
rate-limit.medium.window-seconds=30
